const BACKGROUND_COLOR = '#151517';
const INNER_LINES_COLOR = '#211e28';
const OUTER_LINES_COLOR = '#322d3a';
const FONT_COLOR = '#e8fff2';

export {BACKGROUND_COLOR, INNER_LINES_COLOR, OUTER_LINES_COLOR, FONT_COLOR};